### ISSUE TITLE
在Xpocket里面使用arthas jad报数组越界错误

### ISSUE THREAD

**Issue by smallDot** [PerfMa/xpocket#5]
Exception in thread "Thread-6" java.lang.ArrayIndexOutOfBoundsException: 1024
        at com.perfma.xpocket.plugin.arthas.ArthasPlugin.run(ArthasPlugin.java:236)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ferdiknight** [comment]
是Arthas插件实现中的bug，我会安排修复，感谢提交

**Comment by ferdiknight** [comment]
@smallDot 问题已经修复了，可以下载修复后的体验包 [XPocket.tar.gz](https://a.perfma.net/xpocket/download/XPocket.tar.gz) , [XPocket.zip](https://a.perfma.net/xpocket/download/XPocket.zip)  或者直接下载单独插件 [xpocket-plugin-arthas](https://plugin.xpocket.perfma.com/plugin/52)

**Comment by ferdiknight** [comment]
问题修复关闭issue
